Dashboard/dashboards/urls.py
from django.contrib import admin
from django.urls import path
from article_dashboard import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles_list',views.show),
    path('summary_edit/<int:id>', views.summary_edit),
    path('summary_update/<int:id>', views.summary_update),
]

Dashboard/article_dashboard/models.py
from django.db import models


class Articlemetadata(models.Model):
    article = models.ForeignKey('Articles', models.DO_NOTHING, blank=True, null=True)
    categories = models.TextField(blank=True, null=True)
    image_url = models.TextField(blank=True, null=True)
    engagement_data = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ArticleMetadata'


class Articles(models.Model):
    id = models.CharField(primary_key=True, max_length=255)
    title = models.TextField()
    content = models.TextField(blank=True, null=True)
    published_date = models.DateTimeField(blank=True, null=True)
    author = models.CharField(max_length=255, blank=True, null=True)
    url = models.TextField()
    source = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Articles'


class Summaries(models.Model):
    id = models.IntegerField(primary_key=True)
    article = models.ForeignKey(Articles, models.DO_NOTHING, blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    is_bad = models.IntegerField(blank=True, null=True)
    generated_date = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Summaries'

Dashboard/article_dashboard/forms.py
from django import forms  
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from article_dashboard.models import Summaries, Articles 


class SummariesForm(forms.ModelForm):  
    ''' Form for Summaries model'''
    class Meta:  
        model = Summaries  
        fields = '__all__'


class ArticlesList(forms.Form):
    ''' Form for main view - "articles_list" '''
    date_from = forms.DateField()
    date_to = forms.DateField()
    articles = forms.ModelMultipleChoiceField(Articles.objects.all())
    
    def clean(self):
        ''' Clean and validate valies of date period'''
        cleaned_data = super().clean()
        date_from = cleaned_data.get("date_from")
        date_to = cleaned_data.get("date_to")

        if date_from > date_to:
            raise forms.ValidationError("Start date must be less then end date.")

Dashboard/article_dashboard/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from rest_framework import serializers
from article_dashboard.models import Articles, Summaries
from article_dashboard.forms import SummariesForm, ArticlesList
from datetime import datetime, timedelta


def show(request):
    '''
    Show list of articles with summaries.
    '''
    
    # receive dates from request
    date_from = request.GET.get('date_from')
    date_to = request.GET.get('date_to')
  
    if not (date_from and date_to):
        # if dates are not found, 
        # calculate dates period for the last 30 days
        date_from = datetime.now().date() - timedelta(days=30)
        date_to = datetime.now().date()

        # prepare data, use filter for dates period
        articles = Articles.objects.all().filter(published_date__range=[date_from, date_to]).order_by('-published_date')
        summaries = Summaries.objects.all()

        return render(request,"articles_list.html",context=
            {'articles':articles, 'summaries':summaries, 'date_from':date_from, 'date_to':date_to})
    
    else:
        # form pass validation to cautch error with non-correct period of dates (start date more then end date)
        form = ArticlesList(request.GET)
        form.is_valid()  

        # prepare data, use filter for dates period
        articles = Articles.objects.all().filter(published_date__range=[date_from, date_to]).order_by('-published_date')
        summaries = Summaries.objects.all()
        
        # pass additional parameter "form" to "context" for validation needs
        return render(request,"articles_list.html",context=
            {'articles':articles, 'summaries':summaries, 'date_from':date_from, 'date_to':date_to, 'form':form})
        

def summary_edit(request, id):  
    summary = Summaries.objects.get(id=id)  
    return render(request,'summary_edit.html', {'summary':summary}) 


def summary_update(request, id): 
    summary= Summaries.objects.get(id=id) 

    if request.method=="POST":
        try: 
            form = SummariesForm(request.POST)
            if form.is_valid():
                form.save()
            else:
                # if form is not valid,
                # prepare values for saving
                is_bad = request.POST.get('is_bad')
                if is_bad == 'on':
                    is_bad = True
                else:
                    is_bad =  False
                summ = request.POST.get('summary').strip()
                article = str(request.POST.get('article'))
                
                # if not found related Article, return 404
                try:
                    toSave = Summaries(id=id, is_bad=is_bad, summary=summ, article=Articles.objects.get(pk=article))
                    toSave.save()
                except ObjectDoesNotExist:
                    return HttpResponse(status=404)

            # if success, redirect to main view
            return redirect("/articles_list")  
        
        except KeyError:
            return HttpResponse(status=400)

    # if not success, turn to "summary_edit" view
    return render(request, 'summary_edit.html', {'summary': summary}) 

Dashboard/article_dashboard/templates/articles_list.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Articles</title>  
     {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
    <div class="data-zen-title">
        <img src="/static/img/data-zen-title.jpg" alt="Data Zen News Bot title" width="100%"/>
    </div>
    <div class="data-zen">
        <img src="/static/img/data-zen.png" alt="Data Zen News Bot" width="75"/>
        <h3>
            LIST OF ARTICLES WITH SUMMARIES
        </h3>
    </div>
    <form method="GET" class="get-form">
        <div class="error">{{ form.non_field_errors }}</div>
        <p>Filter date:</p>
        <div class="filter">         
            <label for="date_from">from</label>
            <input type="date" id="date_from" name="date_from" value="{{ date_from }}">
        </div>
        <div class="filter">
            <label for="date_to">to</label>
            <input type="date" id="date_to" name="date_to" value="{{ date_to }}">
        </div>
        <div class="submit">
            <button type="submit">Submit</button>
        </div>
        <table>  
            <thead>  
            <tr>  
                <th>Title</th>  
                <th>Content</th>  
                <th>Published date</th>  
                <th>Author</th>  
                <th>Link to source</th> 
                <th>Summaries</th>  
            </tr>  
            </thead>  
            <tbody>  
        {% for article in articles %}  
            <tr>  
                <td>{{ article.title }}</td>  
                <td>{{ article.content }}</td>  
                <td>{{ article.published_date }}</td>  
                <td>{{ article.author }}</td> 
                <td><a href="{{ article.url }}">link</a></td>
                
                <td>
                    <table>
                        <tbody>
                            <thead>  
                                <tr>  
                                    <th>Summary</th>  
                                    <th>Generated date</th>  
                                    <th>Bad flag</th>  
                                </tr>  
                            </thead>
                        {% for summary in article.summaries_set.all %} 
                            <tr>
                                <td>{{ summary.summary }}</td>
                                <td>{{ summary.generated_date }}</td>
                                <td>  
                                    <div>
                                        <input type="checkbox" id="bad_summary" name="bad_summary" onclick="return false;" {% if summary.is_bad == 1 %} checked {% endif %}/>
                                    </div>
                                    <a href="/summary_edit/{{ summary.id }}"><span class="glyphicon glyphicon-pencil" >{% if summary.is_bad == 1 %} Mark good summary {% else %} Mark Bad summary {% endif %}</span></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </td>
            </tr>  
        {% endfor %}  
            </tbody>  
        </table>  
    </form>
</body>  
</html>  

Dashboard/article_dashboard/templates/summary_edit.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
    <meta charset="UTF-8">  
    <title>Edit</title>  
    {% load static %}  
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>  
</head>  
<body>  
<form method="POST" class="post-form" action="/summary_update/{{summary.id}}">  
    
    {% csrf_token %} 

    <h3>Update bad flag for summary:</h3>   

    <input type="hidden" name="id" id="sid" value="{{ summary.id }}"/>

    <input type="hidden" name="article" id="aid" value="{{ summary.article.id }}"/>

    <div class="form-group-row">
        <textarea rows="20" cols="120" name="summary" id="summary" placeholder="Summary" readonly>
            {{ summary.summary }}
        </textarea>
    </div>
    <div class="form-group-row"> 
        <label for="generated_date">Generated date</label>
        <input type="text" name="generated_date" id="generated_date" value="{{ summary.generated_date }}" readonly/>
    </div>
    <div class="form-group-row">  
        <input type="checkbox" name="is_bad" id="is_bad" {% if summary.is_bad == 1 %} checked {% endif %}/>
        <label for="is_bad">Bad summary</label>
    </div>  
    </div class="form-group-row">   
        <button type="submit">Update</button>
    </div>  
</form>  
</body>  
</html>  